import Vue from 'vue'
import Router from 'vue-router'
import { interopDefault } from './utils'
import scrollBehavior from './router.scrollBehavior.js'

const _7a6dbb4c = () => interopDefault(import('~/pages/dashboard/sales/index.vue' /* webpackChunkName: "" */))
const _400261c4 = () => interopDefault(import('../pages/widgets/index.vue' /* webpackChunkName: "pages/widgets/index" */))
const _77d6b362 = () => interopDefault(import('../pages/account/forgot-password.vue' /* webpackChunkName: "pages/account/forgot-password" */))
const _75a04833 = () => interopDefault(import('../pages/account/login.vue' /* webpackChunkName: "pages/account/login" */))
const _0582ffc9 = () => interopDefault(import('../pages/account/register.vue' /* webpackChunkName: "pages/account/register" */))
const _3af4b4aa = () => interopDefault(import('../pages/apps/calendar/index.vue' /* webpackChunkName: "pages/apps/calendar/index" */))
const _469704c4 = () => interopDefault(import('../pages/apps/chat/index.vue' /* webpackChunkName: "pages/apps/chat/index" */))
const _44542585 = () => interopDefault(import('../pages/apps/companies/index.vue' /* webpackChunkName: "pages/apps/companies/index" */))
const _cfae4df6 = () => interopDefault(import('../pages/apps/file-manager.vue' /* webpackChunkName: "pages/apps/file-manager" */))
const _3130b95e = () => interopDefault(import('../pages/apps/tickets/index.vue' /* webpackChunkName: "pages/apps/tickets/index" */))
const _373740d7 = () => interopDefault(import('../pages/auth/confirm-mail.vue' /* webpackChunkName: "pages/auth/confirm-mail" */))
const _40d7583c = () => interopDefault(import('../pages/auth/confirm-mail-2.vue' /* webpackChunkName: "pages/auth/confirm-mail-2" */))
const _a6d6782a = () => interopDefault(import('../pages/auth/lock-screen.vue' /* webpackChunkName: "pages/auth/lock-screen" */))
const _563f3360 = () => interopDefault(import('../pages/auth/lock-screen-2.vue' /* webpackChunkName: "pages/auth/lock-screen-2" */))
const _87557374 = () => interopDefault(import('../pages/auth/login.vue' /* webpackChunkName: "pages/auth/login" */))
const _12ec842a = () => interopDefault(import('../pages/auth/login-2.vue' /* webpackChunkName: "pages/auth/login-2" */))
const _1b648afd = () => interopDefault(import('../pages/auth/logout.vue' /* webpackChunkName: "pages/auth/logout" */))
const _624a9e3c = () => interopDefault(import('../pages/auth/logout-2.vue' /* webpackChunkName: "pages/auth/logout-2" */))
const _25232868 = () => interopDefault(import('../pages/auth/recoverpwd.vue' /* webpackChunkName: "pages/auth/recoverpwd" */))
const _45ef99f1 = () => interopDefault(import('../pages/auth/recoverpwd-2.vue' /* webpackChunkName: "pages/auth/recoverpwd-2" */))
const _45cde4d6 = () => interopDefault(import('../pages/auth/register.vue' /* webpackChunkName: "pages/auth/register" */))
const _0454f87b = () => interopDefault(import('../pages/auth/register-2.vue' /* webpackChunkName: "pages/auth/register-2" */))
const _8ef5f300 = () => interopDefault(import('../pages/auth/signin-signup.vue' /* webpackChunkName: "pages/auth/signin-signup" */))
const _b46b50b6 = () => interopDefault(import('../pages/auth/signin-signup-2.vue' /* webpackChunkName: "pages/auth/signin-signup-2" */))
const _2565d4cb = () => interopDefault(import('../pages/charts/apex/index.vue' /* webpackChunkName: "pages/charts/apex/index" */))
const _c406ec4e = () => interopDefault(import('../pages/charts/c3/index.vue' /* webpackChunkName: "pages/charts/c3/index" */))
const _47ebac15 = () => interopDefault(import('../pages/charts/chartist/index.vue' /* webpackChunkName: "pages/charts/chartist/index" */))
const _48f20398 = () => interopDefault(import('../pages/charts/chartjs/index.vue' /* webpackChunkName: "pages/charts/chartjs/index" */))
const _0dfd5f9c = () => interopDefault(import('../pages/charts/knob.vue' /* webpackChunkName: "pages/charts/knob" */))
const _69204af4 = () => interopDefault(import('../pages/contacts/list.vue' /* webpackChunkName: "pages/contacts/list" */))
const _3752e771 = () => interopDefault(import('../pages/contacts/profile.vue' /* webpackChunkName: "pages/contacts/profile" */))
const _1183513a = () => interopDefault(import('../pages/dashboard/analytics/index.vue' /* webpackChunkName: "pages/dashboard/analytics/index" */))
const _c1c21f5c = () => interopDefault(import('../pages/dashboard/crm/index.vue' /* webpackChunkName: "pages/dashboard/crm/index" */))
const _1d0d43c0 = () => interopDefault(import('../pages/dashboard/sales/index.vue' /* webpackChunkName: "pages/dashboard/sales/index" */))
const _1bdfe9da = () => interopDefault(import('../pages/ecommerce/cart.vue' /* webpackChunkName: "pages/ecommerce/cart" */))
const _275f34b9 = () => interopDefault(import('../pages/ecommerce/checkout.vue' /* webpackChunkName: "pages/ecommerce/checkout" */))
const _27e40e16 = () => interopDefault(import('../pages/ecommerce/customers/index.vue' /* webpackChunkName: "pages/ecommerce/customers/index" */))
const _c2151a6a = () => interopDefault(import('../pages/ecommerce/data-products.js' /* webpackChunkName: "pages/ecommerce/data-products" */))
const _3e1604a3 = () => interopDefault(import('../pages/ecommerce/order-detail.vue' /* webpackChunkName: "pages/ecommerce/order-detail" */))
const _4884dbca = () => interopDefault(import('../pages/ecommerce/orders/index.vue' /* webpackChunkName: "pages/ecommerce/orders/index" */))
const _3b97b0cd = () => interopDefault(import('../pages/ecommerce/product-create.vue' /* webpackChunkName: "pages/ecommerce/product-create" */))
const _49de031a = () => interopDefault(import('../pages/ecommerce/products/index.vue' /* webpackChunkName: "pages/ecommerce/products/index" */))
const _0f53962c = () => interopDefault(import('../pages/ecommerce/products-grid.vue' /* webpackChunkName: "pages/ecommerce/products-grid" */))
const _5394cb9e = () => interopDefault(import('../pages/ecommerce/sellers.vue' /* webpackChunkName: "pages/ecommerce/sellers" */))
const _6e7d3655 = () => interopDefault(import('../pages/email/data-inbox.js' /* webpackChunkName: "pages/email/data-inbox" */))
const _9e9ac702 = () => interopDefault(import('../pages/email/inbox.vue' /* webpackChunkName: "pages/email/inbox" */))
const _87749df4 = () => interopDefault(import('../pages/email/sidepanel.vue' /* webpackChunkName: "pages/email/sidepanel" */))
const _33ea9332 = () => interopDefault(import('../pages/email/templates.vue' /* webpackChunkName: "pages/email/templates" */))
const _79532298 = () => interopDefault(import('../pages/email/toolbar.vue' /* webpackChunkName: "pages/email/toolbar" */))
const _c08396e8 = () => interopDefault(import('../pages/extended/rangeslider.vue' /* webpackChunkName: "pages/extended/rangeslider" */))
const _1d8f78fd = () => interopDefault(import('../pages/extended/scrollspy.vue' /* webpackChunkName: "pages/extended/scrollspy" */))
const _01e023ed = () => interopDefault(import('../pages/extended/sweet-alert.vue' /* webpackChunkName: "pages/extended/sweet-alert" */))
const _572985cc = () => interopDefault(import('../pages/extended/tour.vue' /* webpackChunkName: "pages/extended/tour" */))
const _8445eee0 = () => interopDefault(import('../pages/extras/404.vue' /* webpackChunkName: "pages/extras/404" */))
const _32d0acec = () => interopDefault(import('../pages/extras/404-alt.vue' /* webpackChunkName: "pages/extras/404-alt" */))
const _1aea3466 = () => interopDefault(import('../pages/extras/500.vue' /* webpackChunkName: "pages/extras/500" */))
const _0794a6c2 = () => interopDefault(import('../pages/extras/coming-soon.vue' /* webpackChunkName: "pages/extras/coming-soon" */))
const _58d93916 = () => interopDefault(import('../pages/extras/faqs.vue' /* webpackChunkName: "pages/extras/faqs" */))
const _6eafbff6 = () => interopDefault(import('../pages/extras/invoice.vue' /* webpackChunkName: "pages/extras/invoice" */))
const _7395e84d = () => interopDefault(import('../pages/extras/lightbox.vue' /* webpackChunkName: "pages/extras/lightbox" */))
const _33880ceb = () => interopDefault(import('../pages/extras/maintenance.vue' /* webpackChunkName: "pages/extras/maintenance" */))
const _58e8881e = () => interopDefault(import('../pages/extras/pricing.vue' /* webpackChunkName: "pages/extras/pricing" */))
const _9dd343ae = () => interopDefault(import('../pages/extras/search-results.vue' /* webpackChunkName: "pages/extras/search-results" */))
const _6d9d858d = () => interopDefault(import('../pages/extras/sitemap.vue' /* webpackChunkName: "pages/extras/sitemap" */))
const _a948c732 = () => interopDefault(import('../pages/extras/starter.vue' /* webpackChunkName: "pages/extras/starter" */))
const _42dfe4ce = () => interopDefault(import('../pages/extras/timeline.vue' /* webpackChunkName: "pages/extras/timeline" */))
const _289d1e06 = () => interopDefault(import('../pages/forms/advanced.vue' /* webpackChunkName: "pages/forms/advanced" */))
const _6244045b = () => interopDefault(import('../pages/forms/elements.vue' /* webpackChunkName: "pages/forms/elements" */))
const _47c150b6 = () => interopDefault(import('../pages/forms/file-uploads.vue' /* webpackChunkName: "pages/forms/file-uploads" */))
const _0ac36460 = () => interopDefault(import('../pages/forms/mask.vue' /* webpackChunkName: "pages/forms/mask" */))
const _8857a35e = () => interopDefault(import('../pages/forms/quill.vue' /* webpackChunkName: "pages/forms/quill" */))
const _654f17dd = () => interopDefault(import('../pages/forms/validation.vue' /* webpackChunkName: "pages/forms/validation" */))
const _3259d1cf = () => interopDefault(import('../pages/forms/wizard.vue' /* webpackChunkName: "pages/forms/wizard" */))
const _700ab288 = () => interopDefault(import('../pages/icons/boxicons.vue' /* webpackChunkName: "pages/icons/boxicons" */))
const _46985336 = () => interopDefault(import('../pages/icons/data-fontawesome.js' /* webpackChunkName: "pages/icons/data-fontawesome" */))
const _4dfda6e4 = () => interopDefault(import('../pages/icons/data-material.js' /* webpackChunkName: "pages/icons/data-material" */))
const _1ada89b0 = () => interopDefault(import('../pages/icons/data-remix.js' /* webpackChunkName: "pages/icons/data-remix" */))
const _714ddb4c = () => interopDefault(import('../pages/icons/feather.vue' /* webpackChunkName: "pages/icons/feather" */))
const _58ceb3be = () => interopDefault(import('../pages/icons/font-awesome.vue' /* webpackChunkName: "pages/icons/font-awesome" */))
const _4e447769 = () => interopDefault(import('../pages/icons/mdi.vue' /* webpackChunkName: "pages/icons/mdi" */))
const _547ea9c0 = () => interopDefault(import('../pages/icons/remix.vue' /* webpackChunkName: "pages/icons/remix" */))
const _aaee1daa = () => interopDefault(import('../pages/icons/weather.vue' /* webpackChunkName: "pages/icons/weather" */))
const _09291fdd = () => interopDefault(import('../pages/maps/google.vue' /* webpackChunkName: "pages/maps/google" */))
const _9afcee8a = () => interopDefault(import('../pages/tables/advanced/index.vue' /* webpackChunkName: "pages/tables/advanced/index" */))
const _743f2e08 = () => interopDefault(import('../pages/tables/basic.vue' /* webpackChunkName: "pages/tables/basic" */))
const _29e0de47 = () => interopDefault(import('../pages/task/detail.vue' /* webpackChunkName: "pages/task/detail" */))
const _07f57a20 = () => interopDefault(import('../pages/task/kanban/index.vue' /* webpackChunkName: "pages/task/kanban/index" */))
const _cb6430d8 = () => interopDefault(import('../pages/task/list.vue' /* webpackChunkName: "pages/task/list" */))
const _49726d43 = () => interopDefault(import('../pages/ui/avatars.vue' /* webpackChunkName: "pages/ui/avatars" */))
const _6e3471ec = () => interopDefault(import('../pages/ui/buttons.vue' /* webpackChunkName: "pages/ui/buttons" */))
const _07bbd62c = () => interopDefault(import('../pages/ui/cards.vue' /* webpackChunkName: "pages/ui/cards" */))
const _4ee914a7 = () => interopDefault(import('../pages/ui/carousel.vue' /* webpackChunkName: "pages/ui/carousel" */))
const _7c59454b = () => interopDefault(import('../pages/ui/dropdowns.vue' /* webpackChunkName: "pages/ui/dropdowns" */))
const _651b04f1 = () => interopDefault(import('../pages/ui/general.vue' /* webpackChunkName: "pages/ui/general" */))
const _e118e9e6 = () => interopDefault(import('../pages/ui/grid.vue' /* webpackChunkName: "pages/ui/grid" */))
const _4133497f = () => interopDefault(import('../pages/ui/images.vue' /* webpackChunkName: "pages/ui/images" */))
const _43fc7817 = () => interopDefault(import('../pages/ui/list-group.vue' /* webpackChunkName: "pages/ui/list-group" */))
const _4111fb6d = () => interopDefault(import('../pages/ui/modals.vue' /* webpackChunkName: "pages/ui/modals" */))
const _3b80f831 = () => interopDefault(import('../pages/ui/notifications.vue' /* webpackChunkName: "pages/ui/notifications" */))
const _4b3ff080 = () => interopDefault(import('../pages/ui/portlets.vue' /* webpackChunkName: "pages/ui/portlets" */))
const _132a46f4 = () => interopDefault(import('../pages/ui/progress.vue' /* webpackChunkName: "pages/ui/progress" */))
const _2dcaa034 = () => interopDefault(import('../pages/ui/ribbons.vue' /* webpackChunkName: "pages/ui/ribbons" */))
const _993ab07e = () => interopDefault(import('../pages/ui/spinners.vue' /* webpackChunkName: "pages/ui/spinners" */))
const _749cd3e3 = () => interopDefault(import('../pages/ui/tabs-accordions.vue' /* webpackChunkName: "pages/ui/tabs-accordions" */))
const _2878a7d8 = () => interopDefault(import('../pages/ui/tooltips-popovers.vue' /* webpackChunkName: "pages/ui/tooltips-popovers" */))
const _2c653936 = () => interopDefault(import('../pages/ui/typography.vue' /* webpackChunkName: "pages/ui/typography" */))
const _64beb744 = () => interopDefault(import('../pages/ui/video.vue' /* webpackChunkName: "pages/ui/video" */))
const _ef3c087e = () => interopDefault(import('../pages/widgets/data.js' /* webpackChunkName: "pages/widgets/data" */))
const _7b1f73d4 = () => interopDefault(import('../pages/apps/calendar/data-calendar.js' /* webpackChunkName: "pages/apps/calendar/data-calendar" */))
const _2eb762e7 = () => interopDefault(import('../pages/apps/chat/data.js' /* webpackChunkName: "pages/apps/chat/data" */))
const _79d08030 = () => interopDefault(import('../pages/apps/companies/data.js' /* webpackChunkName: "pages/apps/companies/data" */))
const _1f6f7e98 = () => interopDefault(import('../pages/apps/tickets/data.js' /* webpackChunkName: "pages/apps/tickets/data" */))
const _ad8eeea4 = () => interopDefault(import('../pages/charts/apex/data.js' /* webpackChunkName: "pages/charts/apex/data" */))
const _7e75293c = () => interopDefault(import('../pages/charts/c3/data.js' /* webpackChunkName: "pages/charts/c3/data" */))
const _be00ab10 = () => interopDefault(import('../pages/charts/chartist/data.js' /* webpackChunkName: "pages/charts/chartist/data" */))
const _d34b3e8e = () => interopDefault(import('../pages/charts/chartjs/BarChart.vue' /* webpackChunkName: "pages/charts/chartjs/BarChart" */))
const _8d323dec = () => interopDefault(import('../pages/charts/chartjs/DonutChart.vue' /* webpackChunkName: "pages/charts/chartjs/DonutChart" */))
const _6fd4b6e8 = () => interopDefault(import('../pages/charts/chartjs/LineChart.vue' /* webpackChunkName: "pages/charts/chartjs/LineChart" */))
const _417c4360 = () => interopDefault(import('../pages/charts/chartjs/PieChart.vue' /* webpackChunkName: "pages/charts/chartjs/PieChart" */))
const _940f9f24 = () => interopDefault(import('../pages/charts/chartjs/PolarChart.vue' /* webpackChunkName: "pages/charts/chartjs/PolarChart" */))
const _30fc3da6 = () => interopDefault(import('../pages/charts/chartjs/RadarChart.vue' /* webpackChunkName: "pages/charts/chartjs/RadarChart" */))
const _2813e4d0 = () => interopDefault(import('../pages/dashboard/analytics/channels.vue' /* webpackChunkName: "pages/dashboard/analytics/channels" */))
const _d4284a7e = () => interopDefault(import('../pages/dashboard/analytics/overview.vue' /* webpackChunkName: "pages/dashboard/analytics/overview" */))
const _04f26d4c = () => interopDefault(import('../pages/dashboard/analytics/social-media.vue' /* webpackChunkName: "pages/dashboard/analytics/social-media" */))
const _ae5725c0 = () => interopDefault(import('../pages/dashboard/analytics/sources.vue' /* webpackChunkName: "pages/dashboard/analytics/sources" */))
const _56ed2b70 = () => interopDefault(import('../pages/dashboard/analytics/users.vue' /* webpackChunkName: "pages/dashboard/analytics/users" */))
const _090faf58 = () => interopDefault(import('../pages/ecommerce/customers/data.js' /* webpackChunkName: "pages/ecommerce/customers/data" */))
const _75ff59fe = () => interopDefault(import('../pages/ecommerce/orders/data.js' /* webpackChunkName: "pages/ecommerce/orders/data" */))
const _5735febd = () => interopDefault(import('../pages/ecommerce/products/data.js' /* webpackChunkName: "pages/ecommerce/products/data" */))
const _a6df0ec4 = () => interopDefault(import('../pages/tables/advanced/data.js' /* webpackChunkName: "pages/tables/advanced/data" */))
const _64b73c13 = () => interopDefault(import('../pages/task/kanban/data.js' /* webpackChunkName: "pages/task/kanban/data" */))
const _a4c1bb66 = () => interopDefault(import('../pages/ecommerce/product-detail/_id.vue' /* webpackChunkName: "pages/ecommerce/product-detail/_id" */))
const _0a18512c = () => interopDefault(import('../pages/email/reademail/_id.vue' /* webpackChunkName: "pages/email/reademail/_id" */))

// TODO: remove in Nuxt 3
const emptyFn = () => {}
const originalPush = Router.prototype.push
Router.prototype.push = function push (location, onComplete = emptyFn, onAbort) {
  return originalPush.call(this, location, onComplete, onAbort)
}

Vue.use(Router)

export const routerOptions = {
  mode: 'history',
  base: decodeURI('/'),
  linkActiveClass: 'nuxt-link-active',
  linkExactActiveClass: 'nuxt-link-exact-active',
  scrollBehavior,

  routes: [{
    path: "/ar",
    component: _7a6dbb4c
  }, {
    path: "/es",
    component: _7a6dbb4c
  }, {
    path: "/fr",
    component: _7a6dbb4c
  }, {
    path: "/widgets",
    component: _400261c4,
    name: "widgets___en"
  }, {
    path: "/account/forgot-password",
    component: _77d6b362,
    name: "account-forgot-password___en"
  }, {
    path: "/account/login",
    component: _75a04833,
    name: "account-login___en"
  }, {
    path: "/account/register",
    component: _0582ffc9,
    name: "account-register___en"
  }, {
    path: "/apps/calendar",
    component: _3af4b4aa,
    name: "apps-calendar___en"
  }, {
    path: "/apps/chat",
    component: _469704c4,
    name: "apps-chat___en"
  }, {
    path: "/apps/companies",
    component: _44542585,
    name: "apps-companies___en"
  }, {
    path: "/apps/file-manager",
    component: _cfae4df6,
    name: "apps-file-manager___en"
  }, {
    path: "/apps/tickets",
    component: _3130b95e,
    name: "apps-tickets___en"
  }, {
    path: "/ar/widgets",
    component: _400261c4,
    name: "widgets___ar"
  }, {
    path: "/auth/confirm-mail",
    component: _373740d7,
    name: "auth-confirm-mail___en"
  }, {
    path: "/auth/confirm-mail-2",
    component: _40d7583c,
    name: "auth-confirm-mail-2___en"
  }, {
    path: "/auth/lock-screen",
    component: _a6d6782a,
    name: "auth-lock-screen___en"
  }, {
    path: "/auth/lock-screen-2",
    component: _563f3360,
    name: "auth-lock-screen-2___en"
  }, {
    path: "/auth/login",
    component: _87557374,
    name: "auth-login___en"
  }, {
    path: "/auth/login-2",
    component: _12ec842a,
    name: "auth-login-2___en"
  }, {
    path: "/auth/logout",
    component: _1b648afd,
    name: "auth-logout___en"
  }, {
    path: "/auth/logout-2",
    component: _624a9e3c,
    name: "auth-logout-2___en"
  }, {
    path: "/auth/recoverpwd",
    component: _25232868,
    name: "auth-recoverpwd___en"
  }, {
    path: "/auth/recoverpwd-2",
    component: _45ef99f1,
    name: "auth-recoverpwd-2___en"
  }, {
    path: "/auth/register",
    component: _45cde4d6,
    name: "auth-register___en"
  }, {
    path: "/auth/register-2",
    component: _0454f87b,
    name: "auth-register-2___en"
  }, {
    path: "/auth/signin-signup",
    component: _8ef5f300,
    name: "auth-signin-signup___en"
  }, {
    path: "/auth/signin-signup-2",
    component: _b46b50b6,
    name: "auth-signin-signup-2___en"
  }, {
    path: "/charts/apex",
    component: _2565d4cb,
    name: "charts-apex___en"
  }, {
    path: "/charts/c3",
    component: _c406ec4e,
    name: "charts-c3___en"
  }, {
    path: "/charts/chartist",
    component: _47ebac15,
    name: "charts-chartist___en"
  }, {
    path: "/charts/chartjs",
    component: _48f20398,
    name: "charts-chartjs___en"
  }, {
    path: "/charts/knob",
    component: _0dfd5f9c,
    name: "charts-knob___en"
  }, {
    path: "/contacts/list",
    component: _69204af4,
    name: "contacts-list___en"
  }, {
    path: "/contacts/profile",
    component: _3752e771,
    name: "contacts-profile___en"
  }, {
    path: "/dashboard/analytics",
    component: _1183513a,
    name: "dashboard-analytics___en"
  }, {
    path: "/dashboard/crm",
    component: _c1c21f5c,
    name: "dashboard-crm___en"
  }, {
    path: "/dashboard/sales",
    component: _1d0d43c0,
    name: "dashboard-sales___en"
  }, {
    path: "/ecommerce/cart",
    component: _1bdfe9da,
    name: "ecommerce-cart___en"
  }, {
    path: "/ecommerce/checkout",
    component: _275f34b9,
    name: "ecommerce-checkout___en"
  }, {
    path: "/ecommerce/customers",
    component: _27e40e16,
    name: "ecommerce-customers___en"
  }, {
    path: "/ecommerce/data-products",
    component: _c2151a6a,
    name: "ecommerce-data-products___en"
  }, {
    path: "/ecommerce/order-detail",
    component: _3e1604a3,
    name: "ecommerce-order-detail___en"
  }, {
    path: "/ecommerce/orders",
    component: _4884dbca,
    name: "ecommerce-orders___en"
  }, {
    path: "/ecommerce/product-create",
    component: _3b97b0cd,
    name: "ecommerce-product-create___en"
  }, {
    path: "/ecommerce/products",
    component: _49de031a,
    name: "ecommerce-products___en"
  }, {
    path: "/ecommerce/products-grid",
    component: _0f53962c,
    name: "ecommerce-products-grid___en"
  }, {
    path: "/ecommerce/sellers",
    component: _5394cb9e,
    name: "ecommerce-sellers___en"
  }, {
    path: "/email/data-inbox",
    component: _6e7d3655,
    name: "email-data-inbox___en"
  }, {
    path: "/email/inbox",
    component: _9e9ac702,
    name: "email-inbox___en"
  }, {
    path: "/email/sidepanel",
    component: _87749df4,
    name: "email-sidepanel___en"
  }, {
    path: "/email/templates",
    component: _33ea9332,
    name: "email-templates___en"
  }, {
    path: "/email/toolbar",
    component: _79532298,
    name: "email-toolbar___en"
  }, {
    path: "/es/widgets",
    component: _400261c4,
    name: "widgets___es"
  }, {
    path: "/extended/rangeslider",
    component: _c08396e8,
    name: "extended-rangeslider___en"
  }, {
    path: "/extended/scrollspy",
    component: _1d8f78fd,
    name: "extended-scrollspy___en"
  }, {
    path: "/extended/sweet-alert",
    component: _01e023ed,
    name: "extended-sweet-alert___en"
  }, {
    path: "/extended/tour",
    component: _572985cc,
    name: "extended-tour___en"
  }, {
    path: "/extras/404",
    component: _8445eee0,
    name: "extras-404___en"
  }, {
    path: "/extras/404-alt",
    component: _32d0acec,
    name: "extras-404-alt___en"
  }, {
    path: "/extras/500",
    component: _1aea3466,
    name: "extras-500___en"
  }, {
    path: "/extras/coming-soon",
    component: _0794a6c2,
    name: "extras-coming-soon___en"
  }, {
    path: "/extras/faqs",
    component: _58d93916,
    name: "extras-faqs___en"
  }, {
    path: "/extras/invoice",
    component: _6eafbff6,
    name: "extras-invoice___en"
  }, {
    path: "/extras/lightbox",
    component: _7395e84d,
    name: "extras-lightbox___en"
  }, {
    path: "/extras/maintenance",
    component: _33880ceb,
    name: "extras-maintenance___en"
  }, {
    path: "/extras/pricing",
    component: _58e8881e,
    name: "extras-pricing___en"
  }, {
    path: "/extras/search-results",
    component: _9dd343ae,
    name: "extras-search-results___en"
  }, {
    path: "/extras/sitemap",
    component: _6d9d858d,
    name: "extras-sitemap___en"
  }, {
    path: "/extras/starter",
    component: _a948c732,
    name: "extras-starter___en"
  }, {
    path: "/extras/timeline",
    component: _42dfe4ce,
    name: "extras-timeline___en"
  }, {
    path: "/forms/advanced",
    component: _289d1e06,
    name: "forms-advanced___en"
  }, {
    path: "/forms/elements",
    component: _6244045b,
    name: "forms-elements___en"
  }, {
    path: "/forms/file-uploads",
    component: _47c150b6,
    name: "forms-file-uploads___en"
  }, {
    path: "/forms/mask",
    component: _0ac36460,
    name: "forms-mask___en"
  }, {
    path: "/forms/quill",
    component: _8857a35e,
    name: "forms-quill___en"
  }, {
    path: "/forms/validation",
    component: _654f17dd,
    name: "forms-validation___en"
  }, {
    path: "/forms/wizard",
    component: _3259d1cf,
    name: "forms-wizard___en"
  }, {
    path: "/fr/widgets",
    component: _400261c4,
    name: "widgets___fr"
  }, {
    path: "/icons/boxicons",
    component: _700ab288,
    name: "icons-boxicons___en"
  }, {
    path: "/icons/data-fontawesome",
    component: _46985336,
    name: "icons-data-fontawesome___en"
  }, {
    path: "/icons/data-material",
    component: _4dfda6e4,
    name: "icons-data-material___en"
  }, {
    path: "/icons/data-remix",
    component: _1ada89b0,
    name: "icons-data-remix___en"
  }, {
    path: "/icons/feather",
    component: _714ddb4c,
    name: "icons-feather___en"
  }, {
    path: "/icons/font-awesome",
    component: _58ceb3be,
    name: "icons-font-awesome___en"
  }, {
    path: "/icons/mdi",
    component: _4e447769,
    name: "icons-mdi___en"
  }, {
    path: "/icons/remix",
    component: _547ea9c0,
    name: "icons-remix___en"
  }, {
    path: "/icons/weather",
    component: _aaee1daa,
    name: "icons-weather___en"
  }, {
    path: "/maps/google",
    component: _09291fdd,
    name: "maps-google___en"
  }, {
    path: "/tables/advanced",
    component: _9afcee8a,
    name: "tables-advanced___en"
  }, {
    path: "/tables/basic",
    component: _743f2e08,
    name: "tables-basic___en"
  }, {
    path: "/task/detail",
    component: _29e0de47,
    name: "task-detail___en"
  }, {
    path: "/task/kanban",
    component: _07f57a20,
    name: "task-kanban___en"
  }, {
    path: "/task/list",
    component: _cb6430d8,
    name: "task-list___en"
  }, {
    path: "/ui/avatars",
    component: _49726d43,
    name: "ui-avatars___en"
  }, {
    path: "/ui/buttons",
    component: _6e3471ec,
    name: "ui-buttons___en"
  }, {
    path: "/ui/cards",
    component: _07bbd62c,
    name: "ui-cards___en"
  }, {
    path: "/ui/carousel",
    component: _4ee914a7,
    name: "ui-carousel___en"
  }, {
    path: "/ui/dropdowns",
    component: _7c59454b,
    name: "ui-dropdowns___en"
  }, {
    path: "/ui/general",
    component: _651b04f1,
    name: "ui-general___en"
  }, {
    path: "/ui/grid",
    component: _e118e9e6,
    name: "ui-grid___en"
  }, {
    path: "/ui/images",
    component: _4133497f,
    name: "ui-images___en"
  }, {
    path: "/ui/list-group",
    component: _43fc7817,
    name: "ui-list-group___en"
  }, {
    path: "/ui/modals",
    component: _4111fb6d,
    name: "ui-modals___en"
  }, {
    path: "/ui/notifications",
    component: _3b80f831,
    name: "ui-notifications___en"
  }, {
    path: "/ui/portlets",
    component: _4b3ff080,
    name: "ui-portlets___en"
  }, {
    path: "/ui/progress",
    component: _132a46f4,
    name: "ui-progress___en"
  }, {
    path: "/ui/ribbons",
    component: _2dcaa034,
    name: "ui-ribbons___en"
  }, {
    path: "/ui/spinners",
    component: _993ab07e,
    name: "ui-spinners___en"
  }, {
    path: "/ui/tabs-accordions",
    component: _749cd3e3,
    name: "ui-tabs-accordions___en"
  }, {
    path: "/ui/tooltips-popovers",
    component: _2878a7d8,
    name: "ui-tooltips-popovers___en"
  }, {
    path: "/ui/typography",
    component: _2c653936,
    name: "ui-typography___en"
  }, {
    path: "/ui/video",
    component: _64beb744,
    name: "ui-video___en"
  }, {
    path: "/widgets/data",
    component: _ef3c087e,
    name: "widgets-data___en"
  }, {
    path: "/apps/calendar/data-calendar",
    component: _7b1f73d4,
    name: "apps-calendar-data-calendar___en"
  }, {
    path: "/apps/chat/data",
    component: _2eb762e7,
    name: "apps-chat-data___en"
  }, {
    path: "/apps/companies/data",
    component: _79d08030,
    name: "apps-companies-data___en"
  }, {
    path: "/apps/tickets/data",
    component: _1f6f7e98,
    name: "apps-tickets-data___en"
  }, {
    path: "/ar/account/forgot-password",
    component: _77d6b362,
    name: "account-forgot-password___ar"
  }, {
    path: "/ar/account/login",
    component: _75a04833,
    name: "account-login___ar"
  }, {
    path: "/ar/account/register",
    component: _0582ffc9,
    name: "account-register___ar"
  }, {
    path: "/ar/apps/calendar",
    component: _3af4b4aa,
    name: "apps-calendar___ar"
  }, {
    path: "/ar/apps/chat",
    component: _469704c4,
    name: "apps-chat___ar"
  }, {
    path: "/ar/apps/companies",
    component: _44542585,
    name: "apps-companies___ar"
  }, {
    path: "/ar/apps/file-manager",
    component: _cfae4df6,
    name: "apps-file-manager___ar"
  }, {
    path: "/ar/apps/tickets",
    component: _3130b95e,
    name: "apps-tickets___ar"
  }, {
    path: "/ar/auth/confirm-mail",
    component: _373740d7,
    name: "auth-confirm-mail___ar"
  }, {
    path: "/ar/auth/confirm-mail-2",
    component: _40d7583c,
    name: "auth-confirm-mail-2___ar"
  }, {
    path: "/ar/auth/lock-screen",
    component: _a6d6782a,
    name: "auth-lock-screen___ar"
  }, {
    path: "/ar/auth/lock-screen-2",
    component: _563f3360,
    name: "auth-lock-screen-2___ar"
  }, {
    path: "/ar/auth/login",
    component: _87557374,
    name: "auth-login___ar"
  }, {
    path: "/ar/auth/login-2",
    component: _12ec842a,
    name: "auth-login-2___ar"
  }, {
    path: "/ar/auth/logout",
    component: _1b648afd,
    name: "auth-logout___ar"
  }, {
    path: "/ar/auth/logout-2",
    component: _624a9e3c,
    name: "auth-logout-2___ar"
  }, {
    path: "/ar/auth/recoverpwd",
    component: _25232868,
    name: "auth-recoverpwd___ar"
  }, {
    path: "/ar/auth/recoverpwd-2",
    component: _45ef99f1,
    name: "auth-recoverpwd-2___ar"
  }, {
    path: "/ar/auth/register",
    component: _45cde4d6,
    name: "auth-register___ar"
  }, {
    path: "/ar/auth/register-2",
    component: _0454f87b,
    name: "auth-register-2___ar"
  }, {
    path: "/ar/auth/signin-signup",
    component: _8ef5f300,
    name: "auth-signin-signup___ar"
  }, {
    path: "/ar/auth/signin-signup-2",
    component: _b46b50b6,
    name: "auth-signin-signup-2___ar"
  }, {
    path: "/ar/charts/apex",
    component: _2565d4cb,
    name: "charts-apex___ar"
  }, {
    path: "/ar/charts/c3",
    component: _c406ec4e,
    name: "charts-c3___ar"
  }, {
    path: "/ar/charts/chartist",
    component: _47ebac15,
    name: "charts-chartist___ar"
  }, {
    path: "/ar/charts/chartjs",
    component: _48f20398,
    name: "charts-chartjs___ar"
  }, {
    path: "/ar/charts/knob",
    component: _0dfd5f9c,
    name: "charts-knob___ar"
  }, {
    path: "/ar/contacts/list",
    component: _69204af4,
    name: "contacts-list___ar"
  }, {
    path: "/ar/contacts/profile",
    component: _3752e771,
    name: "contacts-profile___ar"
  }, {
    path: "/ar/dashboard/analytics",
    component: _1183513a,
    name: "dashboard-analytics___ar"
  }, {
    path: "/ar/dashboard/crm",
    component: _c1c21f5c,
    name: "dashboard-crm___ar"
  }, {
    path: "/ar/dashboard/sales",
    component: _1d0d43c0,
    name: "dashboard-sales___ar"
  }, {
    path: "/ar/ecommerce/cart",
    component: _1bdfe9da,
    name: "ecommerce-cart___ar"
  }, {
    path: "/ar/ecommerce/checkout",
    component: _275f34b9,
    name: "ecommerce-checkout___ar"
  }, {
    path: "/ar/ecommerce/customers",
    component: _27e40e16,
    name: "ecommerce-customers___ar"
  }, {
    path: "/ar/ecommerce/data-products",
    component: _c2151a6a,
    name: "ecommerce-data-products___ar"
  }, {
    path: "/ar/ecommerce/order-detail",
    component: _3e1604a3,
    name: "ecommerce-order-detail___ar"
  }, {
    path: "/ar/ecommerce/orders",
    component: _4884dbca,
    name: "ecommerce-orders___ar"
  }, {
    path: "/ar/ecommerce/product-create",
    component: _3b97b0cd,
    name: "ecommerce-product-create___ar"
  }, {
    path: "/ar/ecommerce/products",
    component: _49de031a,
    name: "ecommerce-products___ar"
  }, {
    path: "/ar/ecommerce/products-grid",
    component: _0f53962c,
    name: "ecommerce-products-grid___ar"
  }, {
    path: "/ar/ecommerce/sellers",
    component: _5394cb9e,
    name: "ecommerce-sellers___ar"
  }, {
    path: "/ar/email/data-inbox",
    component: _6e7d3655,
    name: "email-data-inbox___ar"
  }, {
    path: "/ar/email/inbox",
    component: _9e9ac702,
    name: "email-inbox___ar"
  }, {
    path: "/ar/email/sidepanel",
    component: _87749df4,
    name: "email-sidepanel___ar"
  }, {
    path: "/ar/email/templates",
    component: _33ea9332,
    name: "email-templates___ar"
  }, {
    path: "/ar/email/toolbar",
    component: _79532298,
    name: "email-toolbar___ar"
  }, {
    path: "/ar/extended/rangeslider",
    component: _c08396e8,
    name: "extended-rangeslider___ar"
  }, {
    path: "/ar/extended/scrollspy",
    component: _1d8f78fd,
    name: "extended-scrollspy___ar"
  }, {
    path: "/ar/extended/sweet-alert",
    component: _01e023ed,
    name: "extended-sweet-alert___ar"
  }, {
    path: "/ar/extended/tour",
    component: _572985cc,
    name: "extended-tour___ar"
  }, {
    path: "/ar/extras/404",
    component: _8445eee0,
    name: "extras-404___ar"
  }, {
    path: "/ar/extras/404-alt",
    component: _32d0acec,
    name: "extras-404-alt___ar"
  }, {
    path: "/ar/extras/500",
    component: _1aea3466,
    name: "extras-500___ar"
  }, {
    path: "/ar/extras/coming-soon",
    component: _0794a6c2,
    name: "extras-coming-soon___ar"
  }, {
    path: "/ar/extras/faqs",
    component: _58d93916,
    name: "extras-faqs___ar"
  }, {
    path: "/ar/extras/invoice",
    component: _6eafbff6,
    name: "extras-invoice___ar"
  }, {
    path: "/ar/extras/lightbox",
    component: _7395e84d,
    name: "extras-lightbox___ar"
  }, {
    path: "/ar/extras/maintenance",
    component: _33880ceb,
    name: "extras-maintenance___ar"
  }, {
    path: "/ar/extras/pricing",
    component: _58e8881e,
    name: "extras-pricing___ar"
  }, {
    path: "/ar/extras/search-results",
    component: _9dd343ae,
    name: "extras-search-results___ar"
  }, {
    path: "/ar/extras/sitemap",
    component: _6d9d858d,
    name: "extras-sitemap___ar"
  }, {
    path: "/ar/extras/starter",
    component: _a948c732,
    name: "extras-starter___ar"
  }, {
    path: "/ar/extras/timeline",
    component: _42dfe4ce,
    name: "extras-timeline___ar"
  }, {
    path: "/ar/forms/advanced",
    component: _289d1e06,
    name: "forms-advanced___ar"
  }, {
    path: "/ar/forms/elements",
    component: _6244045b,
    name: "forms-elements___ar"
  }, {
    path: "/ar/forms/file-uploads",
    component: _47c150b6,
    name: "forms-file-uploads___ar"
  }, {
    path: "/ar/forms/mask",
    component: _0ac36460,
    name: "forms-mask___ar"
  }, {
    path: "/ar/forms/quill",
    component: _8857a35e,
    name: "forms-quill___ar"
  }, {
    path: "/ar/forms/validation",
    component: _654f17dd,
    name: "forms-validation___ar"
  }, {
    path: "/ar/forms/wizard",
    component: _3259d1cf,
    name: "forms-wizard___ar"
  }, {
    path: "/ar/icons/boxicons",
    component: _700ab288,
    name: "icons-boxicons___ar"
  }, {
    path: "/ar/icons/data-fontawesome",
    component: _46985336,
    name: "icons-data-fontawesome___ar"
  }, {
    path: "/ar/icons/data-material",
    component: _4dfda6e4,
    name: "icons-data-material___ar"
  }, {
    path: "/ar/icons/data-remix",
    component: _1ada89b0,
    name: "icons-data-remix___ar"
  }, {
    path: "/ar/icons/feather",
    component: _714ddb4c,
    name: "icons-feather___ar"
  }, {
    path: "/ar/icons/font-awesome",
    component: _58ceb3be,
    name: "icons-font-awesome___ar"
  }, {
    path: "/ar/icons/mdi",
    component: _4e447769,
    name: "icons-mdi___ar"
  }, {
    path: "/ar/icons/remix",
    component: _547ea9c0,
    name: "icons-remix___ar"
  }, {
    path: "/ar/icons/weather",
    component: _aaee1daa,
    name: "icons-weather___ar"
  }, {
    path: "/ar/maps/google",
    component: _09291fdd,
    name: "maps-google___ar"
  }, {
    path: "/ar/tables/advanced",
    component: _9afcee8a,
    name: "tables-advanced___ar"
  }, {
    path: "/ar/tables/basic",
    component: _743f2e08,
    name: "tables-basic___ar"
  }, {
    path: "/ar/task/detail",
    component: _29e0de47,
    name: "task-detail___ar"
  }, {
    path: "/ar/task/kanban",
    component: _07f57a20,
    name: "task-kanban___ar"
  }, {
    path: "/ar/task/list",
    component: _cb6430d8,
    name: "task-list___ar"
  }, {
    path: "/ar/ui/avatars",
    component: _49726d43,
    name: "ui-avatars___ar"
  }, {
    path: "/ar/ui/buttons",
    component: _6e3471ec,
    name: "ui-buttons___ar"
  }, {
    path: "/ar/ui/cards",
    component: _07bbd62c,
    name: "ui-cards___ar"
  }, {
    path: "/ar/ui/carousel",
    component: _4ee914a7,
    name: "ui-carousel___ar"
  }, {
    path: "/ar/ui/dropdowns",
    component: _7c59454b,
    name: "ui-dropdowns___ar"
  }, {
    path: "/ar/ui/general",
    component: _651b04f1,
    name: "ui-general___ar"
  }, {
    path: "/ar/ui/grid",
    component: _e118e9e6,
    name: "ui-grid___ar"
  }, {
    path: "/ar/ui/images",
    component: _4133497f,
    name: "ui-images___ar"
  }, {
    path: "/ar/ui/list-group",
    component: _43fc7817,
    name: "ui-list-group___ar"
  }, {
    path: "/ar/ui/modals",
    component: _4111fb6d,
    name: "ui-modals___ar"
  }, {
    path: "/ar/ui/notifications",
    component: _3b80f831,
    name: "ui-notifications___ar"
  }, {
    path: "/ar/ui/portlets",
    component: _4b3ff080,
    name: "ui-portlets___ar"
  }, {
    path: "/ar/ui/progress",
    component: _132a46f4,
    name: "ui-progress___ar"
  }, {
    path: "/ar/ui/ribbons",
    component: _2dcaa034,
    name: "ui-ribbons___ar"
  }, {
    path: "/ar/ui/spinners",
    component: _993ab07e,
    name: "ui-spinners___ar"
  }, {
    path: "/ar/ui/tabs-accordions",
    component: _749cd3e3,
    name: "ui-tabs-accordions___ar"
  }, {
    path: "/ar/ui/tooltips-popovers",
    component: _2878a7d8,
    name: "ui-tooltips-popovers___ar"
  }, {
    path: "/ar/ui/typography",
    component: _2c653936,
    name: "ui-typography___ar"
  }, {
    path: "/ar/ui/video",
    component: _64beb744,
    name: "ui-video___ar"
  }, {
    path: "/ar/widgets/data",
    component: _ef3c087e,
    name: "widgets-data___ar"
  }, {
    path: "/charts/apex/data",
    component: _ad8eeea4,
    name: "charts-apex-data___en"
  }, {
    path: "/charts/c3/data",
    component: _7e75293c,
    name: "charts-c3-data___en"
  }, {
    path: "/charts/chartist/data",
    component: _be00ab10,
    name: "charts-chartist-data___en"
  }, {
    path: "/charts/chartjs/BarChart",
    component: _d34b3e8e,
    name: "charts-chartjs-BarChart___en"
  }, {
    path: "/charts/chartjs/DonutChart",
    component: _8d323dec,
    name: "charts-chartjs-DonutChart___en"
  }, {
    path: "/charts/chartjs/LineChart",
    component: _6fd4b6e8,
    name: "charts-chartjs-LineChart___en"
  }, {
    path: "/charts/chartjs/PieChart",
    component: _417c4360,
    name: "charts-chartjs-PieChart___en"
  }, {
    path: "/charts/chartjs/PolarChart",
    component: _940f9f24,
    name: "charts-chartjs-PolarChart___en"
  }, {
    path: "/charts/chartjs/RadarChart",
    component: _30fc3da6,
    name: "charts-chartjs-RadarChart___en"
  }, {
    path: "/dashboard/analytics/channels",
    component: _2813e4d0,
    name: "dashboard-analytics-channels___en"
  }, {
    path: "/dashboard/analytics/overview",
    component: _d4284a7e,
    name: "dashboard-analytics-overview___en"
  }, {
    path: "/dashboard/analytics/social-media",
    component: _04f26d4c,
    name: "dashboard-analytics-social-media___en"
  }, {
    path: "/dashboard/analytics/sources",
    component: _ae5725c0,
    name: "dashboard-analytics-sources___en"
  }, {
    path: "/dashboard/analytics/users",
    component: _56ed2b70,
    name: "dashboard-analytics-users___en"
  }, {
    path: "/ecommerce/customers/data",
    component: _090faf58,
    name: "ecommerce-customers-data___en"
  }, {
    path: "/ecommerce/orders/data",
    component: _75ff59fe,
    name: "ecommerce-orders-data___en"
  }, {
    path: "/ecommerce/products/data",
    component: _5735febd,
    name: "ecommerce-products-data___en"
  }, {
    path: "/es/account/forgot-password",
    component: _77d6b362,
    name: "account-forgot-password___es"
  }, {
    path: "/es/account/login",
    component: _75a04833,
    name: "account-login___es"
  }, {
    path: "/es/account/register",
    component: _0582ffc9,
    name: "account-register___es"
  }, {
    path: "/es/apps/calendar",
    component: _3af4b4aa,
    name: "apps-calendar___es"
  }, {
    path: "/es/apps/chat",
    component: _469704c4,
    name: "apps-chat___es"
  }, {
    path: "/es/apps/companies",
    component: _44542585,
    name: "apps-companies___es"
  }, {
    path: "/es/apps/file-manager",
    component: _cfae4df6,
    name: "apps-file-manager___es"
  }, {
    path: "/es/apps/tickets",
    component: _3130b95e,
    name: "apps-tickets___es"
  }, {
    path: "/es/auth/confirm-mail",
    component: _373740d7,
    name: "auth-confirm-mail___es"
  }, {
    path: "/es/auth/confirm-mail-2",
    component: _40d7583c,
    name: "auth-confirm-mail-2___es"
  }, {
    path: "/es/auth/lock-screen",
    component: _a6d6782a,
    name: "auth-lock-screen___es"
  }, {
    path: "/es/auth/lock-screen-2",
    component: _563f3360,
    name: "auth-lock-screen-2___es"
  }, {
    path: "/es/auth/login",
    component: _87557374,
    name: "auth-login___es"
  }, {
    path: "/es/auth/login-2",
    component: _12ec842a,
    name: "auth-login-2___es"
  }, {
    path: "/es/auth/logout",
    component: _1b648afd,
    name: "auth-logout___es"
  }, {
    path: "/es/auth/logout-2",
    component: _624a9e3c,
    name: "auth-logout-2___es"
  }, {
    path: "/es/auth/recoverpwd",
    component: _25232868,
    name: "auth-recoverpwd___es"
  }, {
    path: "/es/auth/recoverpwd-2",
    component: _45ef99f1,
    name: "auth-recoverpwd-2___es"
  }, {
    path: "/es/auth/register",
    component: _45cde4d6,
    name: "auth-register___es"
  }, {
    path: "/es/auth/register-2",
    component: _0454f87b,
    name: "auth-register-2___es"
  }, {
    path: "/es/auth/signin-signup",
    component: _8ef5f300,
    name: "auth-signin-signup___es"
  }, {
    path: "/es/auth/signin-signup-2",
    component: _b46b50b6,
    name: "auth-signin-signup-2___es"
  }, {
    path: "/es/charts/apex",
    component: _2565d4cb,
    name: "charts-apex___es"
  }, {
    path: "/es/charts/c3",
    component: _c406ec4e,
    name: "charts-c3___es"
  }, {
    path: "/es/charts/chartist",
    component: _47ebac15,
    name: "charts-chartist___es"
  }, {
    path: "/es/charts/chartjs",
    component: _48f20398,
    name: "charts-chartjs___es"
  }, {
    path: "/es/charts/knob",
    component: _0dfd5f9c,
    name: "charts-knob___es"
  }, {
    path: "/es/contacts/list",
    component: _69204af4,
    name: "contacts-list___es"
  }, {
    path: "/es/contacts/profile",
    component: _3752e771,
    name: "contacts-profile___es"
  }, {
    path: "/es/dashboard/analytics",
    component: _1183513a,
    name: "dashboard-analytics___es"
  }, {
    path: "/es/dashboard/crm",
    component: _c1c21f5c,
    name: "dashboard-crm___es"
  }, {
    path: "/es/dashboard/sales",
    component: _1d0d43c0,
    name: "dashboard-sales___es"
  }, {
    path: "/es/ecommerce/cart",
    component: _1bdfe9da,
    name: "ecommerce-cart___es"
  }, {
    path: "/es/ecommerce/checkout",
    component: _275f34b9,
    name: "ecommerce-checkout___es"
  }, {
    path: "/es/ecommerce/customers",
    component: _27e40e16,
    name: "ecommerce-customers___es"
  }, {
    path: "/es/ecommerce/data-products",
    component: _c2151a6a,
    name: "ecommerce-data-products___es"
  }, {
    path: "/es/ecommerce/order-detail",
    component: _3e1604a3,
    name: "ecommerce-order-detail___es"
  }, {
    path: "/es/ecommerce/orders",
    component: _4884dbca,
    name: "ecommerce-orders___es"
  }, {
    path: "/es/ecommerce/product-create",
    component: _3b97b0cd,
    name: "ecommerce-product-create___es"
  }, {
    path: "/es/ecommerce/products",
    component: _49de031a,
    name: "ecommerce-products___es"
  }, {
    path: "/es/ecommerce/products-grid",
    component: _0f53962c,
    name: "ecommerce-products-grid___es"
  }, {
    path: "/es/ecommerce/sellers",
    component: _5394cb9e,
    name: "ecommerce-sellers___es"
  }, {
    path: "/es/email/data-inbox",
    component: _6e7d3655,
    name: "email-data-inbox___es"
  }, {
    path: "/es/email/inbox",
    component: _9e9ac702,
    name: "email-inbox___es"
  }, {
    path: "/es/email/sidepanel",
    component: _87749df4,
    name: "email-sidepanel___es"
  }, {
    path: "/es/email/templates",
    component: _33ea9332,
    name: "email-templates___es"
  }, {
    path: "/es/email/toolbar",
    component: _79532298,
    name: "email-toolbar___es"
  }, {
    path: "/es/extended/rangeslider",
    component: _c08396e8,
    name: "extended-rangeslider___es"
  }, {
    path: "/es/extended/scrollspy",
    component: _1d8f78fd,
    name: "extended-scrollspy___es"
  }, {
    path: "/es/extended/sweet-alert",
    component: _01e023ed,
    name: "extended-sweet-alert___es"
  }, {
    path: "/es/extended/tour",
    component: _572985cc,
    name: "extended-tour___es"
  }, {
    path: "/es/extras/404",
    component: _8445eee0,
    name: "extras-404___es"
  }, {
    path: "/es/extras/404-alt",
    component: _32d0acec,
    name: "extras-404-alt___es"
  }, {
    path: "/es/extras/500",
    component: _1aea3466,
    name: "extras-500___es"
  }, {
    path: "/es/extras/coming-soon",
    component: _0794a6c2,
    name: "extras-coming-soon___es"
  }, {
    path: "/es/extras/faqs",
    component: _58d93916,
    name: "extras-faqs___es"
  }, {
    path: "/es/extras/invoice",
    component: _6eafbff6,
    name: "extras-invoice___es"
  }, {
    path: "/es/extras/lightbox",
    component: _7395e84d,
    name: "extras-lightbox___es"
  }, {
    path: "/es/extras/maintenance",
    component: _33880ceb,
    name: "extras-maintenance___es"
  }, {
    path: "/es/extras/pricing",
    component: _58e8881e,
    name: "extras-pricing___es"
  }, {
    path: "/es/extras/search-results",
    component: _9dd343ae,
    name: "extras-search-results___es"
  }, {
    path: "/es/extras/sitemap",
    component: _6d9d858d,
    name: "extras-sitemap___es"
  }, {
    path: "/es/extras/starter",
    component: _a948c732,
    name: "extras-starter___es"
  }, {
    path: "/es/extras/timeline",
    component: _42dfe4ce,
    name: "extras-timeline___es"
  }, {
    path: "/es/forms/advanced",
    component: _289d1e06,
    name: "forms-advanced___es"
  }, {
    path: "/es/forms/elements",
    component: _6244045b,
    name: "forms-elements___es"
  }, {
    path: "/es/forms/file-uploads",
    component: _47c150b6,
    name: "forms-file-uploads___es"
  }, {
    path: "/es/forms/mask",
    component: _0ac36460,
    name: "forms-mask___es"
  }, {
    path: "/es/forms/quill",
    component: _8857a35e,
    name: "forms-quill___es"
  }, {
    path: "/es/forms/validation",
    component: _654f17dd,
    name: "forms-validation___es"
  }, {
    path: "/es/forms/wizard",
    component: _3259d1cf,
    name: "forms-wizard___es"
  }, {
    path: "/es/icons/boxicons",
    component: _700ab288,
    name: "icons-boxicons___es"
  }, {
    path: "/es/icons/data-fontawesome",
    component: _46985336,
    name: "icons-data-fontawesome___es"
  }, {
    path: "/es/icons/data-material",
    component: _4dfda6e4,
    name: "icons-data-material___es"
  }, {
    path: "/es/icons/data-remix",
    component: _1ada89b0,
    name: "icons-data-remix___es"
  }, {
    path: "/es/icons/feather",
    component: _714ddb4c,
    name: "icons-feather___es"
  }, {
    path: "/es/icons/font-awesome",
    component: _58ceb3be,
    name: "icons-font-awesome___es"
  }, {
    path: "/es/icons/mdi",
    component: _4e447769,
    name: "icons-mdi___es"
  }, {
    path: "/es/icons/remix",
    component: _547ea9c0,
    name: "icons-remix___es"
  }, {
    path: "/es/icons/weather",
    component: _aaee1daa,
    name: "icons-weather___es"
  }, {
    path: "/es/maps/google",
    component: _09291fdd,
    name: "maps-google___es"
  }, {
    path: "/es/tables/advanced",
    component: _9afcee8a,
    name: "tables-advanced___es"
  }, {
    path: "/es/tables/basic",
    component: _743f2e08,
    name: "tables-basic___es"
  }, {
    path: "/es/task/detail",
    component: _29e0de47,
    name: "task-detail___es"
  }, {
    path: "/es/task/kanban",
    component: _07f57a20,
    name: "task-kanban___es"
  }, {
    path: "/es/task/list",
    component: _cb6430d8,
    name: "task-list___es"
  }, {
    path: "/es/ui/avatars",
    component: _49726d43,
    name: "ui-avatars___es"
  }, {
    path: "/es/ui/buttons",
    component: _6e3471ec,
    name: "ui-buttons___es"
  }, {
    path: "/es/ui/cards",
    component: _07bbd62c,
    name: "ui-cards___es"
  }, {
    path: "/es/ui/carousel",
    component: _4ee914a7,
    name: "ui-carousel___es"
  }, {
    path: "/es/ui/dropdowns",
    component: _7c59454b,
    name: "ui-dropdowns___es"
  }, {
    path: "/es/ui/general",
    component: _651b04f1,
    name: "ui-general___es"
  }, {
    path: "/es/ui/grid",
    component: _e118e9e6,
    name: "ui-grid___es"
  }, {
    path: "/es/ui/images",
    component: _4133497f,
    name: "ui-images___es"
  }, {
    path: "/es/ui/list-group",
    component: _43fc7817,
    name: "ui-list-group___es"
  }, {
    path: "/es/ui/modals",
    component: _4111fb6d,
    name: "ui-modals___es"
  }, {
    path: "/es/ui/notifications",
    component: _3b80f831,
    name: "ui-notifications___es"
  }, {
    path: "/es/ui/portlets",
    component: _4b3ff080,
    name: "ui-portlets___es"
  }, {
    path: "/es/ui/progress",
    component: _132a46f4,
    name: "ui-progress___es"
  }, {
    path: "/es/ui/ribbons",
    component: _2dcaa034,
    name: "ui-ribbons___es"
  }, {
    path: "/es/ui/spinners",
    component: _993ab07e,
    name: "ui-spinners___es"
  }, {
    path: "/es/ui/tabs-accordions",
    component: _749cd3e3,
    name: "ui-tabs-accordions___es"
  }, {
    path: "/es/ui/tooltips-popovers",
    component: _2878a7d8,
    name: "ui-tooltips-popovers___es"
  }, {
    path: "/es/ui/typography",
    component: _2c653936,
    name: "ui-typography___es"
  }, {
    path: "/es/ui/video",
    component: _64beb744,
    name: "ui-video___es"
  }, {
    path: "/es/widgets/data",
    component: _ef3c087e,
    name: "widgets-data___es"
  }, {
    path: "/fr/account/forgot-password",
    component: _77d6b362,
    name: "account-forgot-password___fr"
  }, {
    path: "/fr/account/login",
    component: _75a04833,
    name: "account-login___fr"
  }, {
    path: "/fr/account/register",
    component: _0582ffc9,
    name: "account-register___fr"
  }, {
    path: "/fr/apps/calendar",
    component: _3af4b4aa,
    name: "apps-calendar___fr"
  }, {
    path: "/fr/apps/chat",
    component: _469704c4,
    name: "apps-chat___fr"
  }, {
    path: "/fr/apps/companies",
    component: _44542585,
    name: "apps-companies___fr"
  }, {
    path: "/fr/apps/file-manager",
    component: _cfae4df6,
    name: "apps-file-manager___fr"
  }, {
    path: "/fr/apps/tickets",
    component: _3130b95e,
    name: "apps-tickets___fr"
  }, {
    path: "/fr/auth/confirm-mail",
    component: _373740d7,
    name: "auth-confirm-mail___fr"
  }, {
    path: "/fr/auth/confirm-mail-2",
    component: _40d7583c,
    name: "auth-confirm-mail-2___fr"
  }, {
    path: "/fr/auth/lock-screen",
    component: _a6d6782a,
    name: "auth-lock-screen___fr"
  }, {
    path: "/fr/auth/lock-screen-2",
    component: _563f3360,
    name: "auth-lock-screen-2___fr"
  }, {
    path: "/fr/auth/login",
    component: _87557374,
    name: "auth-login___fr"
  }, {
    path: "/fr/auth/login-2",
    component: _12ec842a,
    name: "auth-login-2___fr"
  }, {
    path: "/fr/auth/logout",
    component: _1b648afd,
    name: "auth-logout___fr"
  }, {
    path: "/fr/auth/logout-2",
    component: _624a9e3c,
    name: "auth-logout-2___fr"
  }, {
    path: "/fr/auth/recoverpwd",
    component: _25232868,
    name: "auth-recoverpwd___fr"
  }, {
    path: "/fr/auth/recoverpwd-2",
    component: _45ef99f1,
    name: "auth-recoverpwd-2___fr"
  }, {
    path: "/fr/auth/register",
    component: _45cde4d6,
    name: "auth-register___fr"
  }, {
    path: "/fr/auth/register-2",
    component: _0454f87b,
    name: "auth-register-2___fr"
  }, {
    path: "/fr/auth/signin-signup",
    component: _8ef5f300,
    name: "auth-signin-signup___fr"
  }, {
    path: "/fr/auth/signin-signup-2",
    component: _b46b50b6,
    name: "auth-signin-signup-2___fr"
  }, {
    path: "/fr/charts/apex",
    component: _2565d4cb,
    name: "charts-apex___fr"
  }, {
    path: "/fr/charts/c3",
    component: _c406ec4e,
    name: "charts-c3___fr"
  }, {
    path: "/fr/charts/chartist",
    component: _47ebac15,
    name: "charts-chartist___fr"
  }, {
    path: "/fr/charts/chartjs",
    component: _48f20398,
    name: "charts-chartjs___fr"
  }, {
    path: "/fr/charts/knob",
    component: _0dfd5f9c,
    name: "charts-knob___fr"
  }, {
    path: "/fr/contacts/list",
    component: _69204af4,
    name: "contacts-list___fr"
  }, {
    path: "/fr/contacts/profile",
    component: _3752e771,
    name: "contacts-profile___fr"
  }, {
    path: "/fr/dashboard/analytics",
    component: _1183513a,
    name: "dashboard-analytics___fr"
  }, {
    path: "/fr/dashboard/crm",
    component: _c1c21f5c,
    name: "dashboard-crm___fr"
  }, {
    path: "/fr/dashboard/sales",
    component: _1d0d43c0,
    name: "dashboard-sales___fr"
  }, {
    path: "/fr/ecommerce/cart",
    component: _1bdfe9da,
    name: "ecommerce-cart___fr"
  }, {
    path: "/fr/ecommerce/checkout",
    component: _275f34b9,
    name: "ecommerce-checkout___fr"
  }, {
    path: "/fr/ecommerce/customers",
    component: _27e40e16,
    name: "ecommerce-customers___fr"
  }, {
    path: "/fr/ecommerce/data-products",
    component: _c2151a6a,
    name: "ecommerce-data-products___fr"
  }, {
    path: "/fr/ecommerce/order-detail",
    component: _3e1604a3,
    name: "ecommerce-order-detail___fr"
  }, {
    path: "/fr/ecommerce/orders",
    component: _4884dbca,
    name: "ecommerce-orders___fr"
  }, {
    path: "/fr/ecommerce/product-create",
    component: _3b97b0cd,
    name: "ecommerce-product-create___fr"
  }, {
    path: "/fr/ecommerce/products",
    component: _49de031a,
    name: "ecommerce-products___fr"
  }, {
    path: "/fr/ecommerce/products-grid",
    component: _0f53962c,
    name: "ecommerce-products-grid___fr"
  }, {
    path: "/fr/ecommerce/sellers",
    component: _5394cb9e,
    name: "ecommerce-sellers___fr"
  }, {
    path: "/fr/email/data-inbox",
    component: _6e7d3655,
    name: "email-data-inbox___fr"
  }, {
    path: "/fr/email/inbox",
    component: _9e9ac702,
    name: "email-inbox___fr"
  }, {
    path: "/fr/email/sidepanel",
    component: _87749df4,
    name: "email-sidepanel___fr"
  }, {
    path: "/fr/email/templates",
    component: _33ea9332,
    name: "email-templates___fr"
  }, {
    path: "/fr/email/toolbar",
    component: _79532298,
    name: "email-toolbar___fr"
  }, {
    path: "/fr/extended/rangeslider",
    component: _c08396e8,
    name: "extended-rangeslider___fr"
  }, {
    path: "/fr/extended/scrollspy",
    component: _1d8f78fd,
    name: "extended-scrollspy___fr"
  }, {
    path: "/fr/extended/sweet-alert",
    component: _01e023ed,
    name: "extended-sweet-alert___fr"
  }, {
    path: "/fr/extended/tour",
    component: _572985cc,
    name: "extended-tour___fr"
  }, {
    path: "/fr/extras/404",
    component: _8445eee0,
    name: "extras-404___fr"
  }, {
    path: "/fr/extras/404-alt",
    component: _32d0acec,
    name: "extras-404-alt___fr"
  }, {
    path: "/fr/extras/500",
    component: _1aea3466,
    name: "extras-500___fr"
  }, {
    path: "/fr/extras/coming-soon",
    component: _0794a6c2,
    name: "extras-coming-soon___fr"
  }, {
    path: "/fr/extras/faqs",
    component: _58d93916,
    name: "extras-faqs___fr"
  }, {
    path: "/fr/extras/invoice",
    component: _6eafbff6,
    name: "extras-invoice___fr"
  }, {
    path: "/fr/extras/lightbox",
    component: _7395e84d,
    name: "extras-lightbox___fr"
  }, {
    path: "/fr/extras/maintenance",
    component: _33880ceb,
    name: "extras-maintenance___fr"
  }, {
    path: "/fr/extras/pricing",
    component: _58e8881e,
    name: "extras-pricing___fr"
  }, {
    path: "/fr/extras/search-results",
    component: _9dd343ae,
    name: "extras-search-results___fr"
  }, {
    path: "/fr/extras/sitemap",
    component: _6d9d858d,
    name: "extras-sitemap___fr"
  }, {
    path: "/fr/extras/starter",
    component: _a948c732,
    name: "extras-starter___fr"
  }, {
    path: "/fr/extras/timeline",
    component: _42dfe4ce,
    name: "extras-timeline___fr"
  }, {
    path: "/fr/forms/advanced",
    component: _289d1e06,
    name: "forms-advanced___fr"
  }, {
    path: "/fr/forms/elements",
    component: _6244045b,
    name: "forms-elements___fr"
  }, {
    path: "/fr/forms/file-uploads",
    component: _47c150b6,
    name: "forms-file-uploads___fr"
  }, {
    path: "/fr/forms/mask",
    component: _0ac36460,
    name: "forms-mask___fr"
  }, {
    path: "/fr/forms/quill",
    component: _8857a35e,
    name: "forms-quill___fr"
  }, {
    path: "/fr/forms/validation",
    component: _654f17dd,
    name: "forms-validation___fr"
  }, {
    path: "/fr/forms/wizard",
    component: _3259d1cf,
    name: "forms-wizard___fr"
  }, {
    path: "/fr/icons/boxicons",
    component: _700ab288,
    name: "icons-boxicons___fr"
  }, {
    path: "/fr/icons/data-fontawesome",
    component: _46985336,
    name: "icons-data-fontawesome___fr"
  }, {
    path: "/fr/icons/data-material",
    component: _4dfda6e4,
    name: "icons-data-material___fr"
  }, {
    path: "/fr/icons/data-remix",
    component: _1ada89b0,
    name: "icons-data-remix___fr"
  }, {
    path: "/fr/icons/feather",
    component: _714ddb4c,
    name: "icons-feather___fr"
  }, {
    path: "/fr/icons/font-awesome",
    component: _58ceb3be,
    name: "icons-font-awesome___fr"
  }, {
    path: "/fr/icons/mdi",
    component: _4e447769,
    name: "icons-mdi___fr"
  }, {
    path: "/fr/icons/remix",
    component: _547ea9c0,
    name: "icons-remix___fr"
  }, {
    path: "/fr/icons/weather",
    component: _aaee1daa,
    name: "icons-weather___fr"
  }, {
    path: "/fr/maps/google",
    component: _09291fdd,
    name: "maps-google___fr"
  }, {
    path: "/fr/tables/advanced",
    component: _9afcee8a,
    name: "tables-advanced___fr"
  }, {
    path: "/fr/tables/basic",
    component: _743f2e08,
    name: "tables-basic___fr"
  }, {
    path: "/fr/task/detail",
    component: _29e0de47,
    name: "task-detail___fr"
  }, {
    path: "/fr/task/kanban",
    component: _07f57a20,
    name: "task-kanban___fr"
  }, {
    path: "/fr/task/list",
    component: _cb6430d8,
    name: "task-list___fr"
  }, {
    path: "/fr/ui/avatars",
    component: _49726d43,
    name: "ui-avatars___fr"
  }, {
    path: "/fr/ui/buttons",
    component: _6e3471ec,
    name: "ui-buttons___fr"
  }, {
    path: "/fr/ui/cards",
    component: _07bbd62c,
    name: "ui-cards___fr"
  }, {
    path: "/fr/ui/carousel",
    component: _4ee914a7,
    name: "ui-carousel___fr"
  }, {
    path: "/fr/ui/dropdowns",
    component: _7c59454b,
    name: "ui-dropdowns___fr"
  }, {
    path: "/fr/ui/general",
    component: _651b04f1,
    name: "ui-general___fr"
  }, {
    path: "/fr/ui/grid",
    component: _e118e9e6,
    name: "ui-grid___fr"
  }, {
    path: "/fr/ui/images",
    component: _4133497f,
    name: "ui-images___fr"
  }, {
    path: "/fr/ui/list-group",
    component: _43fc7817,
    name: "ui-list-group___fr"
  }, {
    path: "/fr/ui/modals",
    component: _4111fb6d,
    name: "ui-modals___fr"
  }, {
    path: "/fr/ui/notifications",
    component: _3b80f831,
    name: "ui-notifications___fr"
  }, {
    path: "/fr/ui/portlets",
    component: _4b3ff080,
    name: "ui-portlets___fr"
  }, {
    path: "/fr/ui/progress",
    component: _132a46f4,
    name: "ui-progress___fr"
  }, {
    path: "/fr/ui/ribbons",
    component: _2dcaa034,
    name: "ui-ribbons___fr"
  }, {
    path: "/fr/ui/spinners",
    component: _993ab07e,
    name: "ui-spinners___fr"
  }, {
    path: "/fr/ui/tabs-accordions",
    component: _749cd3e3,
    name: "ui-tabs-accordions___fr"
  }, {
    path: "/fr/ui/tooltips-popovers",
    component: _2878a7d8,
    name: "ui-tooltips-popovers___fr"
  }, {
    path: "/fr/ui/typography",
    component: _2c653936,
    name: "ui-typography___fr"
  }, {
    path: "/fr/ui/video",
    component: _64beb744,
    name: "ui-video___fr"
  }, {
    path: "/fr/widgets/data",
    component: _ef3c087e,
    name: "widgets-data___fr"
  }, {
    path: "/tables/advanced/data",
    component: _a6df0ec4,
    name: "tables-advanced-data___en"
  }, {
    path: "/task/kanban/data",
    component: _64b73c13,
    name: "task-kanban-data___en"
  }, {
    path: "/ar/apps/calendar/data-calendar",
    component: _7b1f73d4,
    name: "apps-calendar-data-calendar___ar"
  }, {
    path: "/ar/apps/chat/data",
    component: _2eb762e7,
    name: "apps-chat-data___ar"
  }, {
    path: "/ar/apps/companies/data",
    component: _79d08030,
    name: "apps-companies-data___ar"
  }, {
    path: "/ar/apps/tickets/data",
    component: _1f6f7e98,
    name: "apps-tickets-data___ar"
  }, {
    path: "/ar/charts/apex/data",
    component: _ad8eeea4,
    name: "charts-apex-data___ar"
  }, {
    path: "/ar/charts/c3/data",
    component: _7e75293c,
    name: "charts-c3-data___ar"
  }, {
    path: "/ar/charts/chartist/data",
    component: _be00ab10,
    name: "charts-chartist-data___ar"
  }, {
    path: "/ar/charts/chartjs/BarChart",
    component: _d34b3e8e,
    name: "charts-chartjs-BarChart___ar"
  }, {
    path: "/ar/charts/chartjs/DonutChart",
    component: _8d323dec,
    name: "charts-chartjs-DonutChart___ar"
  }, {
    path: "/ar/charts/chartjs/LineChart",
    component: _6fd4b6e8,
    name: "charts-chartjs-LineChart___ar"
  }, {
    path: "/ar/charts/chartjs/PieChart",
    component: _417c4360,
    name: "charts-chartjs-PieChart___ar"
  }, {
    path: "/ar/charts/chartjs/PolarChart",
    component: _940f9f24,
    name: "charts-chartjs-PolarChart___ar"
  }, {
    path: "/ar/charts/chartjs/RadarChart",
    component: _30fc3da6,
    name: "charts-chartjs-RadarChart___ar"
  }, {
    path: "/ar/dashboard/analytics/channels",
    component: _2813e4d0,
    name: "dashboard-analytics-channels___ar"
  }, {
    path: "/ar/dashboard/analytics/overview",
    component: _d4284a7e,
    name: "dashboard-analytics-overview___ar"
  }, {
    path: "/ar/dashboard/analytics/social-media",
    component: _04f26d4c,
    name: "dashboard-analytics-social-media___ar"
  }, {
    path: "/ar/dashboard/analytics/sources",
    component: _ae5725c0,
    name: "dashboard-analytics-sources___ar"
  }, {
    path: "/ar/dashboard/analytics/users",
    component: _56ed2b70,
    name: "dashboard-analytics-users___ar"
  }, {
    path: "/ar/ecommerce/customers/data",
    component: _090faf58,
    name: "ecommerce-customers-data___ar"
  }, {
    path: "/ar/ecommerce/orders/data",
    component: _75ff59fe,
    name: "ecommerce-orders-data___ar"
  }, {
    path: "/ar/ecommerce/products/data",
    component: _5735febd,
    name: "ecommerce-products-data___ar"
  }, {
    path: "/ar/tables/advanced/data",
    component: _a6df0ec4,
    name: "tables-advanced-data___ar"
  }, {
    path: "/ar/task/kanban/data",
    component: _64b73c13,
    name: "task-kanban-data___ar"
  }, {
    path: "/es/apps/calendar/data-calendar",
    component: _7b1f73d4,
    name: "apps-calendar-data-calendar___es"
  }, {
    path: "/es/apps/chat/data",
    component: _2eb762e7,
    name: "apps-chat-data___es"
  }, {
    path: "/es/apps/companies/data",
    component: _79d08030,
    name: "apps-companies-data___es"
  }, {
    path: "/es/apps/tickets/data",
    component: _1f6f7e98,
    name: "apps-tickets-data___es"
  }, {
    path: "/es/charts/apex/data",
    component: _ad8eeea4,
    name: "charts-apex-data___es"
  }, {
    path: "/es/charts/c3/data",
    component: _7e75293c,
    name: "charts-c3-data___es"
  }, {
    path: "/es/charts/chartist/data",
    component: _be00ab10,
    name: "charts-chartist-data___es"
  }, {
    path: "/es/charts/chartjs/BarChart",
    component: _d34b3e8e,
    name: "charts-chartjs-BarChart___es"
  }, {
    path: "/es/charts/chartjs/DonutChart",
    component: _8d323dec,
    name: "charts-chartjs-DonutChart___es"
  }, {
    path: "/es/charts/chartjs/LineChart",
    component: _6fd4b6e8,
    name: "charts-chartjs-LineChart___es"
  }, {
    path: "/es/charts/chartjs/PieChart",
    component: _417c4360,
    name: "charts-chartjs-PieChart___es"
  }, {
    path: "/es/charts/chartjs/PolarChart",
    component: _940f9f24,
    name: "charts-chartjs-PolarChart___es"
  }, {
    path: "/es/charts/chartjs/RadarChart",
    component: _30fc3da6,
    name: "charts-chartjs-RadarChart___es"
  }, {
    path: "/es/dashboard/analytics/channels",
    component: _2813e4d0,
    name: "dashboard-analytics-channels___es"
  }, {
    path: "/es/dashboard/analytics/overview",
    component: _d4284a7e,
    name: "dashboard-analytics-overview___es"
  }, {
    path: "/es/dashboard/analytics/social-media",
    component: _04f26d4c,
    name: "dashboard-analytics-social-media___es"
  }, {
    path: "/es/dashboard/analytics/sources",
    component: _ae5725c0,
    name: "dashboard-analytics-sources___es"
  }, {
    path: "/es/dashboard/analytics/users",
    component: _56ed2b70,
    name: "dashboard-analytics-users___es"
  }, {
    path: "/es/ecommerce/customers/data",
    component: _090faf58,
    name: "ecommerce-customers-data___es"
  }, {
    path: "/es/ecommerce/orders/data",
    component: _75ff59fe,
    name: "ecommerce-orders-data___es"
  }, {
    path: "/es/ecommerce/products/data",
    component: _5735febd,
    name: "ecommerce-products-data___es"
  }, {
    path: "/es/tables/advanced/data",
    component: _a6df0ec4,
    name: "tables-advanced-data___es"
  }, {
    path: "/es/task/kanban/data",
    component: _64b73c13,
    name: "task-kanban-data___es"
  }, {
    path: "/fr/apps/calendar/data-calendar",
    component: _7b1f73d4,
    name: "apps-calendar-data-calendar___fr"
  }, {
    path: "/fr/apps/chat/data",
    component: _2eb762e7,
    name: "apps-chat-data___fr"
  }, {
    path: "/fr/apps/companies/data",
    component: _79d08030,
    name: "apps-companies-data___fr"
  }, {
    path: "/fr/apps/tickets/data",
    component: _1f6f7e98,
    name: "apps-tickets-data___fr"
  }, {
    path: "/fr/charts/apex/data",
    component: _ad8eeea4,
    name: "charts-apex-data___fr"
  }, {
    path: "/fr/charts/c3/data",
    component: _7e75293c,
    name: "charts-c3-data___fr"
  }, {
    path: "/fr/charts/chartist/data",
    component: _be00ab10,
    name: "charts-chartist-data___fr"
  }, {
    path: "/fr/charts/chartjs/BarChart",
    component: _d34b3e8e,
    name: "charts-chartjs-BarChart___fr"
  }, {
    path: "/fr/charts/chartjs/DonutChart",
    component: _8d323dec,
    name: "charts-chartjs-DonutChart___fr"
  }, {
    path: "/fr/charts/chartjs/LineChart",
    component: _6fd4b6e8,
    name: "charts-chartjs-LineChart___fr"
  }, {
    path: "/fr/charts/chartjs/PieChart",
    component: _417c4360,
    name: "charts-chartjs-PieChart___fr"
  }, {
    path: "/fr/charts/chartjs/PolarChart",
    component: _940f9f24,
    name: "charts-chartjs-PolarChart___fr"
  }, {
    path: "/fr/charts/chartjs/RadarChart",
    component: _30fc3da6,
    name: "charts-chartjs-RadarChart___fr"
  }, {
    path: "/fr/dashboard/analytics/channels",
    component: _2813e4d0,
    name: "dashboard-analytics-channels___fr"
  }, {
    path: "/fr/dashboard/analytics/overview",
    component: _d4284a7e,
    name: "dashboard-analytics-overview___fr"
  }, {
    path: "/fr/dashboard/analytics/social-media",
    component: _04f26d4c,
    name: "dashboard-analytics-social-media___fr"
  }, {
    path: "/fr/dashboard/analytics/sources",
    component: _ae5725c0,
    name: "dashboard-analytics-sources___fr"
  }, {
    path: "/fr/dashboard/analytics/users",
    component: _56ed2b70,
    name: "dashboard-analytics-users___fr"
  }, {
    path: "/fr/ecommerce/customers/data",
    component: _090faf58,
    name: "ecommerce-customers-data___fr"
  }, {
    path: "/fr/ecommerce/orders/data",
    component: _75ff59fe,
    name: "ecommerce-orders-data___fr"
  }, {
    path: "/fr/ecommerce/products/data",
    component: _5735febd,
    name: "ecommerce-products-data___fr"
  }, {
    path: "/fr/tables/advanced/data",
    component: _a6df0ec4,
    name: "tables-advanced-data___fr"
  }, {
    path: "/fr/task/kanban/data",
    component: _64b73c13,
    name: "task-kanban-data___fr"
  }, {
    path: "/ar/ecommerce/product-detail/:id?",
    component: _a4c1bb66,
    name: "ecommerce-product-detail-id___ar"
  }, {
    path: "/ar/email/reademail/:id?",
    component: _0a18512c,
    name: "email-reademail-id___ar"
  }, {
    path: "/es/ecommerce/product-detail/:id?",
    component: _a4c1bb66,
    name: "ecommerce-product-detail-id___es"
  }, {
    path: "/es/email/reademail/:id?",
    component: _0a18512c,
    name: "email-reademail-id___es"
  }, {
    path: "/fr/ecommerce/product-detail/:id?",
    component: _a4c1bb66,
    name: "ecommerce-product-detail-id___fr"
  }, {
    path: "/fr/email/reademail/:id?",
    component: _0a18512c,
    name: "email-reademail-id___fr"
  }, {
    path: "/ecommerce/product-detail/:id?",
    component: _a4c1bb66,
    name: "ecommerce-product-detail-id___en"
  }, {
    path: "/email/reademail/:id?",
    component: _0a18512c,
    name: "email-reademail-id___en"
  }, {
    path: "/",
    component: _7a6dbb4c
  }],

  fallback: false
}

export function createRouter () {
  return new Router(routerOptions)
}
